name: merge develop
"on":
  push:
    branches:
      - develop
jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: |
          ls -a
          echo '[user]' >> .git/config
          echo '  name="gregfromstl"' >> .git/config
          echo '  email="gregfromstl@gmail.com"' >> .git/config
          cat .git/config
          npm --no-git-tag-version version patch
          git add package.json
          git commit -m "bump patch version"
          git push -u origin develop

  build_and_deploy:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install --ignore-scripts

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_VITE_API_KEY: "AIzaSyCy-NB4SSzKtJLxG7YKWDTibRrDjdEEsxQ"
          envkey_VITE_AUTH_DOMAIN: "krause-media-dev.firebaseapp.com"
          envkey_VITE_PROJECT_ID: "krause-media-dev"
          envkey_VITE_STORAGE_BUCKET: "krause-media-dev.appspot.com"
          envkey_VITE_MESSAGING_SENDER_ID: "1014641510657"
          envkey_VITE_APP_ID: "1:1014641510657:web:d09d1bdbe9e529967c3300"
          envkey_VITE_MEASUREMENT_ID: "G-JKMGD6MN20"
          envkey_VITE_API_BASE_URL: "https://us-central1-krause-media-dev.cloudfunctions.net"
          file_name: .env

      - run: yarn run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KRAUSE_MEDIA_DEV }}"
          channelId: live
          projectId: krause-media-dev
